import Head from 'next/head'
import Logo from '@/comps/Logo'
import MyButton from '@/comps/Button'
import styled from'styled-components'
import Footer from '@/comps/Footer'
import Header from '@/comps/Header';
import Switch from '@/comps/Switch'
import {useTheme} from '../utils/provider' 
import {useOrder} from '../utils/provider' 
import {useCode, useRC} from '../utils/provider' 


const Wrapper=styled.div`
width:100%;
height:100vh;
display:flex;
flex-direction:column;
justify-content: center;
align-items:center;
`

const Container=styled.div`
width:50rem;
height:65rem;
display:flex;
flex-direction:column;
justify-content: flex-start;
align-items:center;
border:2px solid lightgrey;
border-radius:1rem;
`


const ButtonCon=styled.div`
width:60%;
height:30rem;
display:flex;
flex-direction:column;
justify-content:space-around;
align-items:flex-end;
margin-top:10rem
`

export default function Home() {
  const {theme,setTheme}=useTheme();
  const {order,setOrder}=useOrder();
  const {code,setCode}=useCode();
  const {rc,setRC}=useRC();


  return (
    <div>
      <Head>
        <title>LEBRART</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
      <Container>
       <Header title="setting"/>
       <ButtonCon>

       <Switch 
    onSwitchClick={()=>setTheme(
        theme === 'dark'? 'default' : 'dark'
    )}
    btn={theme=== 'dark' ? 'On' : 'Off'}
/>    <Switch label='Order Method'   onSwitchClick={()=>setOrder(
        order === 'desc'? 'default' : 'desc'
        
    )}
    btn={order=== 'desc' ? 'Desc' : 'Asc' }/>
      <Switch label='Language code' 
         onSwitchClick={()=>setCode(
        code === 'zho'? 'default' : 'zho'
    )}
    btn={ code=== 'zho' ? 'ZHO' : 'ENG'} />
      <Switch label='Author'   />
      <Switch label='Rating Count' 
      onSwitchClick={()=>setRC(
        rc === '1000'? 'default' : '1000'
    )}
    btn={ rc=== '1000' ? '1000' : '100'} />
      <Switch label='Text review' />
       </ButtonCon>
      </Container>
      <Footer/>
      </Wrapper>
    </div>
  )
}
