import Head from 'next/head'
import ax from 'axios';
import Footer from '@/comps/Footer'
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react'
import Nav from '@/comps/Nav'
import { comp_theme, text_theme } from '../../utils/variables'
import { useTheme, useUser, useClublist } from '../../utils/provider'
import ClubCard from '@/comps/ClubCard';
import getAuth from '@/utils/getAuth'

export default function Bookshelf({

}) {

  const { theme } = useTheme();
  const { user } = useUser();
  const { clublist, setClublist } = useClublist();
  const router = useRouter();
  const [clubs, setClubs] = useState([]);
  const [books2, setbooks2] = useState([]);
  const [books3, setbooks3] = useState([]);

  console.log(user)
  useEffect(() => {
      getAuth(user, router)
      
      const getClubs = async (p) => {
          const res = await ax.get("/api/getClubs", {
            headers: {
              "Authorization": `Bearer ${user}`
            }
          })
          setClublist(res.data.clubs)
      }

      getClubs()

  }, [])

  
  
  return <div>
    <Head>
      <title>bookShelf</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='B_Wrapper'>
      <div className='B_Container' >
        <div className='B_Nav'>
        {user ?
        <Nav onClick={()=>router.push('/bookShelf/search')} users= {user.username}  />
        :   <Nav onClick={()=>router.push('/bookShelf/search')}  />  }
        </div>
        <div className='B_Content' >
          <div className='Side_Bar'>
            <div className='Pannel' style={{
              background: comp_theme[theme].label,
              color: text_theme[theme].label
            }}>
               <a onClick={() => router.push('/bookShelf')} > BookShelf</a>
              <a onClick={() => router.push('/comments')} > Comments</a>
              <a  onClick={()=>alert("Constructing")}>  Friends</a>
              <a onClick={() => router.push('/clubs')}> Clubs</a>
              <a  onClick={()=>alert("Constructing")}> Subscription</a>
            </div>
          </div>
          <div className='Feed_Area' style={{ color: text_theme[theme].title }}>
            <div className='Drawers' >
              <div className='lable' >
                <h3 > Popular clubs for your Location</h3>
              </div>
              <div className='Drawer'>
                {clublist != undefined? clublist.map((o) =>
                  <ClubCard key={o._id}
                    onClick={() => router.push(`/clubs/${o._id}`)}
                    // src={IMG_URL+o.image_s}
                    create_date={o.create_date}
                    title={o.title}
                    host={o.host.username}
                    // members={o.member_count}
                  />
                ): null}

              </div>
              
            </div>
          


           
          </div>

        </div>




        <Footer />

      </div>
    </div>
  </div>


}
