import Head from 'next/head'
import ax from 'axios';
import Footer from '@/comps/Footer'
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react'
import Nav from '@/comps/Nav'
import { comp_theme, text_theme } from '../../utils/variables'
import { useTheme,useUser } from '../../utils/provider'
import ClubCard from '@/comps/ClubCard';
export default function Bookshelf({

}) {

  const { theme } = useTheme();
  const { user } = useUser();
  const router = useRouter();
  const [clubs, setClubs] = useState([]);
  const [books2, setbooks2] = useState([]);
  const [books3, setbooks3] = useState([]);



  

  const GetBooks = async (p) => {
    const res = await ax.get("/api/clubs",
      { params: { page: p } })
    setClubs(res.data)
   
  }
  useEffect(() => {
    GetBooks()
  }, [])

  
  
  return <div>
    <Head>
      <title>bookShelf</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='B_Wrapper'>
      <div className='B_Container' >
        <div className='B_Nav'>
        {user ?
        <Nav onClick={()=>router.push('/bookShelf/search')} users= {user.username}  />
        :   <Nav onClick={()=>router.push('/bookShelf/search')}  />  }
        </div>
        <div className='B_Content' >
          <div className='Side_Bar'>
            <div className='Pannel' style={{
              background: comp_theme[theme].label,
              color: text_theme[theme].label
            }}>
              <a onClick={() => router.push('/bookShelf')} > BookShelf</a>
              <a onClick={() => router.push('/comments')} > Comments</a>
              <a> Friends</a>
              <a> Clubs</a>
              <a> Subscription</a>
            </div>
          </div>
          <div className='Feed_Area' style={{ color: text_theme[theme].title }}>
            <div className='Drawers' >
              <div className='lable' >
                <h3 > Popular clubs for your Location</h3>
              </div>
              <div className='Drawer'>
                {clubs.map((o, i) =>
                  <ClubCard key={i}
                    onClick={() => router.push(`/clubs/${o._id}`)}
                    src={o.image}
                    create_date={o.create_date}
                    title={o.title.substr(0, 20) + "..."}
                    host={o.host}
                    members={o.members}
                  />
                )}

              </div>
              
            </div>
          


           
          </div>

        </div>




        <Footer />

      </div>
    </div>
  </div>


}
