import Head from 'next/head'
import Logo from '@/comps/Logo'
import MyButton from '@/comps/Button'
import styled from 'styled-components'
import Footer from '@/comps/Footer'
import InputBox from '@/comps/InputBox'
import { useRouter } from 'next/router';
import { useState } from 'react'
import Nav from '@/comps/Nav'
import BookCard from '@/comps/BookCard'

export default function Home({

}) {
  const router = useRouter();


  return <div>
    <Head>
      <title>bookShelf</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='B_Wrapper'>
      <div className='B_Container'  >
        <div className='B_Nav'>

          <Nav />
        </div>
        <div className='B_Content'>
          <div className='Side_Bar'>
            <div className='Pannel'>
              <a href="/bookShelf"> BookShelf</a>
              <a href="/comments"> Comments</a>
              <a> Friends</a>
              <a> Clubs</a>
              <a> Subscription</a>
            </div>
          </div>
          <div className='Feed_Area'>
            <div className='Drawer'>
            <h3> Popular books for your Location</h3>
            <BookCard/>
            </div>
            <div className='Drawer'>
            <h3> Popular books for your friens</h3>
            <BookCard/>
            </div>
            <div className='Drawer'>
            <h3> Popular books for your clubs</h3>
            <BookCard/>
            </div>
            <div className='Drawer'>
            <h3> Popular books for your age</h3>
            <BookCard/>
            </div>
            <div className='Drawer'>

            </div>
          </div>

        </div>
        <Footer />
      </div>
    </div>
  </div>


}
