import Head from 'next/head'
import Logo from '@/comps/Logo'
import MyButton from '@/comps/Button'
import styled from 'styled-components'
import Footer from '@/comps/Footer'
import InputBox from '@/comps/InputBox'
import { useRouter } from 'next/router';
import { useState } from 'react'
import Nav from '@/comps/Nav'
import BookCard from '@/comps/BookCard'
import CommentCard from '@/comps/CommentCard'
import { comp_theme, text_theme } from '../utils/variables'
import { useTheme } from '../utils/provider'


const user_comments = [
  {
    "booksrc":"http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg",
    "comment": "Classical Mythology is the best text available; an excellent and complete introduction. Its strengths include its thoroughness, readability, informative notes and appendices, glossary, indices, and format.--Richard A. Spencer, Appalachian State University.",
    "usersrc": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cmFuZG9tJTIwcGVvcGxlfGVufDB8fDB8fA%3D%3D&w=1000&q=80",
    "username": "Mary"
  },
  { "booksrc":"http://images.amazon.com/images/P/0002005018.01.LZZZZZZZ.jpg",
    "comment": "I didn't like Burden of Proof but thought I would give this author's books another try. I couldn't finish it so will try no more. He is a good writer but the stories are full of convolution and uninteresting characters. Sadly, I am done.",
    "usersrc": "https://images.pexels.com/photos/372042/pexels-photo-372042.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    "username": "Janny"
  },
  {"booksrc":"http://images.amazon.com/images/P/0671870432.01.LZZZZZZZ.jpg",
    "comment": "A story about a character with no redeeming features.The story contains endless examples of gratuitous sex and bad language.There are many rambling diversions.Avoid at all costs.",
    "usersrc": "https://media.istockphoto.com/photos/young-woman-portrait-in-the-city-picture-id1009749608?k=20&m=1009749608&s=612x612&w=0&h=3bnVp0Y1625uKkSwnp7Uh2_y_prWbgRBH6a_6jRew3g=",
    "username": "Ali"
  },
  {"booksrc":"http://images.amazon.com/images/P/074322678X.01.LZZZZZZZ.jpg",
    "comment": "After reading all Grisham's books, I have tested Scott Turow. I have enjoyed it very much, but I would not recommend it to anyone whose mother tongue is not (American) English.",
    "usersrc": "https://i.pinimg.com/originals/31/94/d7/3194d7c2de116c908a50792ece3a54bd.jpg",
    "username": "Linda"
  },
  {"booksrc":"http://images.amazon.com/images/P/3404921038.01.LZZZZZZZ.jpg",
    "comment": "Really good. I'm a Turow fan and I enjoyed this one a lot!",
    "usersrc": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-YYQX-SEzg1KB0MwqfQLBjs7MasTpU7KiONxC76gz5F4nrDwzDUOQExULtDnNvx60Bh0&usqp=CAU",
    "username": "Alice"
  },
]


export default function Home({

}) {
  const router = useRouter();
  const [comment,setComment]=useState(user_comments)
  const { theme } = useTheme();

  return <div>
    <Head>
      <title>bookShelf</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='C_Wrapper'>
      <div className='Container'  >
        <div className='Nav'>

          <Nav  onClick={()=>router.push('bookShelf/search')}/>
        </div>
        <div className='Content'>
          <div className='Side_Bar'>
            <div className='Pannel' style={{
              background: comp_theme[theme].label,
              color: text_theme[theme].label
            }}>
              <a onClick={() => router.push('/bookShelf')} > BookShelf</a>
              <a onClick={() => router.push('/comments')} > Comments</a>
              <a> Friends</a>
              <a> Clubs</a>
              <a> Subscription</a>
            </div>
          </div>
          <div className='Feed_Area'>
           {comment.map((o,i)=>
           
           <CommentCard  key={i} 
          booksrc= {o.booksrc} 
          comment= {o.comment}
          usersrc= {o.usersrc}
          username= {o.username}
           />
           ) }
           



          </div>

        </div>
        <Footer />
      </div>
    </div>
  </div>


}
