import Head from 'next/head'
import Logo from '@/comps/Logo'
import MyButton from '@/comps/Button'
import styled from'styled-components'
import Footer from '@/comps/Footer' 
import InputBox from '@/comps/InputBox'
const Wrapper=styled.div`
width:100%;
height:100vh;
display:flex;
flex-direction:column;
justify-content: center;
align-items:center;
`

const Container=styled.div`
width:90rem;
height:100rem;
display:flex;
flex-direction:row;
justify-content: flex-start;
align-items:center;
border-radius:2rem;
`
const LocoCon=styled.div`
width:50%;
height:50%;
display:flex;
flex-direction:column;
justify-content: flex-start;
align-items:flex-start;
border-radius:2rem;
`
const CardCon=styled.div`
width:50%;
height:50%;
display:flex;
flex-direction:column;
justify-content:space-around;
align-items:center;
background-color:#84A98C;
margin:10%;
border-radius:1rem
`


const ButtonCon=styled.div`
width:100%;
height:50%;
display:flex;
flex-direction:row;
justify-content:space-around;
align-items:center;
background-color:#84A98C;
margin:10%;
border-radius:1rem
`
const TextCon=styled.p`
width:40%;
justify-content:center;
align-items:center;
font-size:1rem;
text-align:center;
margin:.5rem
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>Echo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
      <Container>
        <LocoCon>
        <Logo/>

        </LocoCon>
        <CardCon>
        <InputBox/>
        <ButtonCon>
        <MyButton routeTo ="/books/" text="Sign Up"/>
        <MyButton text="Log in" routeTo ="/setting"/>
        </ButtonCon>
        </CardCon>
      </Container>
      <Footer/>
      </Wrapper>

    </div>
  )
}
