import Head from 'next/head'
import Logo from '@/comps/Logo'
import MyButton from '@/comps/Button'
import Footer from '@/comps/Footer'
import InputBox from '@/comps/InputBox'
import { useState,useEffect } from 'react'
import { useRouter } from 'next/router';
import { comp_theme, text_theme } from '../utils/variables'
import { useTheme,useUser } from '../utils/provider'
import ax from 'axios'
import getAuth from '@/utils/getAuth'

export default function Home({
  title = "Log in"
}) {
  const { theme } = useTheme();
  const { user, setUser } = useUser();
  const [e_warn, setE_Warn] = useState(false)
  const [warn, setWarn] = useState(false)
  const [loginData, setLoginData] = useState({email: '', password:''})
  const router = useRouter();


  const logIn = async () => {

      const res = await ax.post('/api/login', loginData)

      if(res.data.accessTk){
        setUser(res.data)
        router.push("/bookShelf")
      }
  }

  return <div>
    <Head>
      <title>Echo</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='Wrapper'>
      <div className='Container' >
        <div className='LogoCon'>
          {/* <p className='welcome'>Welcome</p> */}
          <Logo />
          <p className="intro" style={{ color: text_theme[theme].title }}> Echo is a reader social media.
            In the application, each reader can leave and find comments about books. Also, they can record books to their reading list.
            You may see other people’s reading lists, so you can request a friend connection or subscribe to their new comments. We provide a platform where readers can share their thoughts and find the same or different ideas. The way may give you the other aspect of view to read books. . </p>
        </div>
        <div className='CardCon' style={{
          background: comp_theme[theme].label2,
          color: text_theme[theme].label
        }}
        >
          <div className='title'>{title}</div>
          <div className='InputCon'>

            <InputBox text="Email" value={loginData.email} onChange={e => setLoginData({ ...loginData, email: e.target.value })}/>
          {e_warn ? <p style={{ color: "#ba1141" }}><b>The eamil is invalid</b></p> : null}
            <InputBox text="Password" type="password" value={loginData.password} onChange={e => setLoginData({ ...loginData, password: e.target.value })}/>
            {warn ? <p style={{ color: "#ba1141" }}><b>The password is invalid</b></p> : null}
          </div>
          <div className='ButtonCon'>
            <MyButton onClick={() => router.push("/signUp")} text="Sign Up" />
            <MyButton text="Log in" onClick={logIn} />
          </div>
        </div>
      </div>
      <Footer />
    </div>

  </div>

}
