import Head from 'next/head';
import Footer from '@/comps/Footer';
import { useRouter } from 'next/router';
import { useState } from 'react';
import Nav from '@/comps/Nav';
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import InputBox from '@/comps/InputBox';
import Button from '@mui/material/Button';
export default function Home({

}) {
  const router = useRouter();


  return <div>
    <Head>
      <title>Echo</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='s_Wrapper'>
      <div className='Container'  >
        <div className='Nav'>
          <Nav />
        </div>
        <div className='Content'>
          <div className='personInfo'>
            <img src="https://news.artnet.com/app/news-upload/2021/12/RachelUffner-byJasonFrankRothenberg-2015-750x550.jpg" />
            <div className='content'>
            <InputBox text="Account" style={{width:'10rem'}}/>
            <InputBox text="User name"/>
            <InputBox text="Leave of Age"/>
            <InputBox text="Location"/>
            <InputBox text="Gender"/>
            </div>
            <div className='button'>
              <Button variant="contained">Submit</Button>
              </div>
          </div>
          <div className='settingBox'>
              <p>Dark Mode </p>
              <p>Descendant Mode </p>
              <p>Private Mode</p>
              <p>Personal Info </p>
              <p>Favorite Book </p>
              <p>Reading List </p>
              <p>Friends </p>
              <p>Clubs </p>
             
              <Button variant="contained">Log out</Button>
              
          </div>

        </div>
        <Footer />
      </div>
    </div>
  </div>


}
