import Head from 'next/head';
import Footer from '@/comps/Footer';
import { useRouter } from 'next/router';
import { useState } from 'react';
import Nav from '@/comps/Nav';
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import InputBox from '@/comps/InputBox';
import Button from '@mui/material/Button';
import IosSwitch from '@/comps/MuiSwitch'
import Switch from '@/comps/Switch';
import { useTheme } from '../utils/provider'
import { useOrder } from '../utils/provider'
import { comp_theme, text_theme } from '@/utils/variables';
import SwitchBasic from '@/comps/SwitchBasic'
export default function Home({

}) {
  const router = useRouter();
  const { order, setOrder } = useOrder();
  const { theme, setTheme } = useTheme();

  return <div>
    <Head>
      <title>Echo</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='s_Wrapper'>
      <div className='Container'  >
        <div className='Nav'>
          <Nav />
        </div>
        <div className='Content'>
          <div className='personInfo'>
            <img src="https://news.artnet.com/app/news-upload/2021/12/RachelUffner-byJasonFrankRothenberg-2015-750x550.jpg" />
            <div className='content'>
              <InputBox text="Account" style={{ width: '10rem' }} />
              <InputBox text="User name" />
              <InputBox text="Age" />
              <InputBox text="Location" />
              <InputBox text="Gender" />
            </div>
            <div className='button'>
              <Button variant="contained">Submit</Button>
            </div>
          </div>
          <div className='settingBox' style={{ background: comp_theme[theme].label2, color: text_theme[theme].label }}>
            <SwitchBasic
              switchText="Light Mode" switchHandler={() => setTheme(
                theme === 'light' ? 'default' : 'light'
              )} />
            <SwitchBasic
              switchText="Descendant" switchHandler={() => setOrder(
                order === 'desc' ? 'default' : 'desc'
              )} />
            <Switch label='Order Method' onSwitchClick={() => setOrder(
              order === 'desc' ? 'default' : 'desc'

            )}
              btn={order === 'desc' ? 'Desc' : 'Asc'} />
            <Button variant="contained" onClick={() => router.push('/')} >Log out</Button>

          </div>

        </div>
        <Footer />
      </div>

    </div>
  </div>


}
