import Head from 'next/head'
import Logo from '@/comps/Logo'
import MyButton from '@/comps/Button'
import Footer from '@/comps/Footer'
import InputBox from '@/comps/InputBox'
import { useRouter } from 'next/router';
import { IndexCard } from "../comps/IndexCard"
import { useState } from 'react'
import { comp_theme, text_theme } from '../utils/variables'
import { useTheme } from '../utils/provider'

var page = 1
export default function Home({
  title = "Sign Up"
}) {
  const router = useRouter();
  const { theme } = useTheme();
  const [page1, setPage1] = useState(true)
  const [page2, setPage2] = useState(false)
  const [page3, setPage3] = useState(false)
  const [e_warn, setE_Warn] = useState(false)
  const [warn, setWarn] = useState(false)
  const [register, setRegister] = useState({
    email: "",
    password: "",
    username: "",
    gender: "",
    age: "",
    location: ""
  })
  const nextPage = () => {
    if (page1) {
      let emailRegex = /^([A-Za-z\d\.-]+)@([A-Za-z\d-]+)\.([A-Za-z]{2,6})(\.[A-Za-z]{2,6})?$/
      let e_valid =emailRegex.test(register.email)
      let oneLowerCaseLetter = /(?=.+[a-z])/;
      let oneUppperCaseLetter = /(?=[A-Z])/;
      let oneDigit = /(?=.+[0-9])/;
      let oneSpecailCharacter = /(?=.+[!@#$%^&*])/;
      let minmunEnglishCharacter = /(?=.{8,})/;
      let valid =
        oneLowerCaseLetter.test(register.password) &&
        oneUppperCaseLetter.test(register.password) &&
        oneDigit.test(register.password) &&
        oneSpecailCharacter.test(register.password) &&
        minmunEnglishCharacter.test(register.password);

      if (e_valid&& valid  ) {
       
        setPage1(false)
        setPage2(true)
        setPage3(false)
        setWarn(false)
        setE_Warn(false)
      }
      else if(!e_valid)  {
        setE_Warn(true)
        setWarn(false)
      }
      else if(!valid)  {
        setWarn(true)
        setE_Warn(false)
      }
    }


    else if (page2) {
      setPage1(false)
      setPage2(false)
      setPage3(true)
    }
    else{
      router.push("/")
    }
    console.log("page " + page)
  }
  const backPage = () => {
    if (page1) {
      router.push("/")
    }
    else if (page2) {
      setPage1(true)
      setPage2(false)
      setPage3(false)
    }
    else if (page3) {
      setPage1(false)
      setPage2(true)
      setPage3(false)
    }
    console.log("page " + page)
  }

  return <div>
    <Head>
      <title>Echo</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='Wrapper'>
      <div className='Container' >
        <div className='LogoCon'>
          <p style={{ color: 'pink' }} className='welcome'>Welcome to</p>
          <Logo />
          {/* <p className="intro"> Every literate person is aware of the paragraph. Paragraphs are important in speeches, in writing or a random paragraph can be used as a prop in ads or presentations too! They are like the building blocks. </p> */}
        </div>
        {page1 ? (<div className='CardCon' style={{
          background: comp_theme[theme].label2,
          color: text_theme[theme].label
        }}>
          <p className='title'>{title}</p>
          <InputBox text="Email" value={register.email} onChange={e => setRegister({ ...register, email: e.target.value })} />
          {e_warn ? <p style={{ color: "#ba1141" }}><b>The eamil is invalid</b></p> : null}
          <InputBox text="Password" value={register.password} onChange={e => setRegister({ ...register, password: e.target.value })} />
          <p>The password requires a smaall and upper caselettter, a character, a number, and eight digits.</p>
          {warn ? <p style={{ color: "#ba1141" }}><b>The password is invalid</b></p> : null}
          <div className='ButtonCon' >
            <MyButton onClick={backPage} text="Back" />
            <MyButton text="Next" onClick={nextPage} />
          </div>
        </div>)
          : null}
        {page2 ? (<div className='CardCon' style={{
          background: comp_theme[theme].label2,
          color: text_theme[theme].label
        }}>
          <p className='title'>{title}</p>
          <InputBox text="Username" value={register.username} onChange={e => setRegister({ ...register, username: e.target.value })} />
          <InputBox text="Gender" value={register.gender} onChange={e => setRegister({ ...register, gender: e.target.value })} />
          <div className='ButtonCon' >
            <MyButton onClick={backPage} text="Back" />
            <MyButton text="Next" onClick={nextPage} />
          </div>
        </div>)
          : null}
        {page3 ? (<div className='CardCon' style={{
          background: comp_theme[theme].label2,
          color: text_theme[theme].label
        }}>
          <p className='title'>{title}</p>
          <InputBox text="Age" value={register.age} onChange={e => setRegister({ ...register, age: e.target.value })} />
          <InputBox text="Location" value={register.location} onChange={e => setRegister({ ...register, location: e.target.value })} />
          <div className='ButtonCon' >
            <MyButton onClick={backPage} text="Back" />
            <MyButton text="Next" onClick={nextPage} />
          </div>
        </div>)
          : null}
      </div>
      <Footer />
    </div>

  </div>

}
