import Head from 'next/head'
import Logo from '@/comps/Logo'
import MyButton from '@/comps/Button'
import styled from'styled-components'
import Footer from '@/comps/Footer' 
import InputBox from '@/comps/InputBox'


export default function Home({
  title="Sign Up"
}) {
 
  return <div>
      <Head>
        <title>Echo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='Wrapper'>
      <div className='Container' >
        <div className='LogoCon'>
          <p className='welcome'>Welcome to</p>
        <Logo/>
        {/* <p className="intro"> Every literate person is aware of the paragraph. Paragraphs are important in speeches, in writing or a random paragraph can be used as a prop in ads or presentations too! They are like the building blocks. </p> */}
        </div>
        <div className='CardCon'>
        <p className='title'>{title}</p>
        <InputBox/>
        <InputBox text="Password"/>
        <div className='ButtonCon'>
        <MyButton routeTo ="/" text="Back"/>
        <MyButton text="Next" routeTo ="/setting"/>
        </div>
        </div>
      </div>
      <Footer/>
      </div>

    </div>
  
}
