import Head from 'next/head';
import ax from 'axios';
import { useRouter } from 'next/router';
import styled from 'styled-components';
import Footer from '@/comps/Footer';
import { useEffect, useState } from 'react'
import BookCom from '@/comps/BookCom';
import MyButton, { Button } from '@/comps/Button';
import Nav from '@/comps/Nav'
import {comp_theme, text_theme} from'../../utils/variables'
import {useTheme} from '../../utils/provider'

export default function BooksID() {
  const router = useRouter();
  const {id} = router.query;
  const [data, setDate] = useState(null)
  const {theme} = useTheme();

  useEffect(() => {
    if (id) {
      const GetBook = async () => {
        const res = await ax.get("/api/books", {
          params: {
            book_isbn:id,
            }
        });
        // console.log(res.data)
        if (res.data[0]) {
          setDate(res.data[0])
        }
      }
      GetBook()
    }
  }, [id])
  if (data === null) {
    return <div> 404 Can not find the book. </div>
  }
  return <div>
    <Head>
      <title>Echo</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='sB_Wrapper'>
      <div className='Container' >
      <div className='Nav'>
          <Nav />
        </div>
        <div className='Content' >
          <div className='Side_Bar'>

          <BookCom 
            src={data.ImageURLL}

            title={data.BookTitle}
            author={data.BookAuthor}
            ISBN={data.ISBN}
            YearOfPublication={data.YearOfPublication}
            Publisher={data.Publisher}
           
          />
         
          </div>
          <div className='bookComment'>

          </div>
        </div>
      <Footer />
      </div>
    </div>
  </div>
}
