import Head from 'next/head'
import ax from 'axios';
import Footer from '@/comps/Footer'
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react'
import Nav from '@/comps/Nav'
import BookCard from '@/comps/BookCard'
import styled from 'styled-components';
import Button from '@mui/material/Button';
import { comp_theme, text_theme ,order_method} from '../../utils/variables'
import { useTheme,useOrder } from '../../utils/provider'
import MyButton from '@/comps/Button';
let timer = null;
export default function bookShelf({

}) {
  const {order} = useOrder();
  const { theme } = useTheme();
  const router = useRouter();
  const [data, setData] = useState([]);
  const [books2, setbooks2] = useState([]);
  const [books3, setbooks3] = useState([]);
  const [curpage, setCurPage] = useState(1);
  const [publish,setPublish]=useState(false)
  const itemsPerPage = 15;
  var butt_arr = [];
  var start = 1;
  for (var i = 1; i < 1000; i += itemsPerPage) {
    // butt_arr.push(i)
    butt_arr.push(((i - 1) / itemsPerPage) + 1);
    // start++
  }

  butt_arr = butt_arr.slice(
    curpage - 5 < 0 ? 0 : curpage - 5,
    curpage + 5);

  
  const inputFilter = async (txt) => {
    console.log(txt,)
    if (timer) {
      clearTimeout(timer);
      timer = null
    }
    if (timer===null){
      timer= setTimeout(async()=>{
        console.log("async call!!!")
        const res = await ax.get("/api/books_search",{
          params:{
            txt:txt,
           sort_type:order_method[order]?.label,
           year_publish:publish,
          
          }
        })

        console.log(res.data);
        setData(res.data);
        timer=null;
      },1500)
    }
  }
  const OffSort=()=>{
    setPublish(!publish)
  }
  return <div>
    <Head>
      <title>bookShelf</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='B_Wrapper'>
      <div className='B_Container' >
        <div className='B_Nav'>
          <Nav onChange={(e) => inputFilter(e.target.value)}  />
        </div>
        <div className='B_Content' >
          <div className='Side_Bar'>
            <div className='Pannel' style={{
              background: comp_theme[theme].label,
              color: text_theme[theme].label
            }}>
              <a onClick={() => router.push('/bookShelf')} > BookShelf</a>
              <a onClick={() => router.push('/comments')} > Comments</a>
              <a> Friends</a>
              <a> Clubs</a>
              <a> Subscription</a>
            </div>
          </div>
          <div className='Feed_Area' style={{ color: text_theme[theme].title }}>
            <div className='Drawers' >
              <div className='lable' >
                <h3 > Search result</h3>
              </div>
              <div className='Drawer_search'>
                
                {(data===[]) ? <h4> There is no result.</h4>:
               ( data.map((o, i) =>
                  <BookCard key={i}
                    onClick={() => router.push(`/bookShelf/${o.ISBN}`)}
                    src={o.ImageURLS}
                    title={o.BookTitle.substr(0, 20) + "..."}
                    isbn={o.ISBN}
                  />
                )) 
              
              }

              </div>
              {/* <MyButton onClick={()=>GetBooks()}>1</MyButton> */}
            </div>
          


            

          </div>

        </div>




        <Footer />

      </div>
    </div>
  </div>


}
